import type { PlaylistRepository, UserRepository } from '~/repositories/interfaces';
import type {
  CreatePlaylistRequest,
  Playlist,
  PlaylistType,
} from '../../domain/playlist.types';

/**
 * Create playlist use case request
 */
export interface CreatePlaylistUseCaseRequest extends CreatePlaylistRequest {
  userId: string;
}

/**
 * Create playlist use case response
 */
export interface CreatePlaylistUseCaseResponse {
  playlistId: string;
  message: string;
  autoGeneratedThumbnail: boolean;
  suggestedMetadata?: Partial<Playlist['metadata']>;
}

/**
 * Dependencies for the create playlist use case
 */
export interface CreatePlaylistDependencies {
  playlistRepository: PlaylistRepository;
  userRepository: UserRepository;
  logger?: {
    info: (message: string, data?: any) => void;
    error: (message: string, error?: any) => void;
    warn: (message: string, data?: any) => void;
  };
}

/**
 * Additional options for playlist creation
 */
export interface CreatePlaylistOptions {
  generateThumbnailFromFirstVideo?: boolean;
  autoDetectSeries?: boolean;
  validateVideoIds?: boolean;
}
