import { afterEach, beforeEach, describe, expect, test, vi } from 'vitest';

const requireProtectedApiSessionMock = vi.fn();
const resolveServerPlaylistOwnerIdMock = vi.fn();
const fakePlaylistServices = {
  addVideoToPlaylist: { execute: vi.fn() },
  createPlaylist: { execute: vi.fn() },
  deletePlaylist: { execute: vi.fn() },
  findPlaylists: { execute: vi.fn() },
  getPlaylistDetails: { execute: vi.fn() },
  removeVideoFromPlaylist: { execute: vi.fn() },
  reorderPlaylistItems: { execute: vi.fn() },
  updatePlaylist: { execute: vi.fn() },
};

async function importPlaylistsApiRoute() {
  return import('../../../app/routes/api.playlists');
}

async function importPlaylistDetailApiRoute() {
  return import('../../../app/routes/api.playlists.$id');
}

describe('playlist api contract', () => {
  beforeEach(() => {
    vi.resetModules();
    vi.clearAllMocks();
    vi.doMock('~/composition/server/auth', () => ({
      requireProtectedApiSession: requireProtectedApiSessionMock,
    }));
    vi.doMock('~/composition/server/playlist', () => ({
      getServerPlaylistServices: () => fakePlaylistServices,
      resolveServerPlaylistOwnerId: resolveServerPlaylistOwnerIdMock,
    }));
    requireProtectedApiSessionMock.mockResolvedValue(null);
    resolveServerPlaylistOwnerIdMock.mockResolvedValue('owner-1');
  });

  afterEach(() => {
    vi.doUnmock('~/composition/server/auth');
    vi.doUnmock('~/composition/server/playlist');
    vi.resetModules();
  });

  test('list route preserves the current success payload shape', async () => {
    fakePlaylistServices.findPlaylists.execute.mockResolvedValue({
      data: {
        filters: { genre: [], searchQuery: 'vault' },
        hasMore: false,
        pagination: { currentPage: 1, limit: 20, offset: 0, totalPages: 1 },
        playlists: [{ id: 'playlist-1', name: 'Vault', ownerId: 'owner-1', type: 'user_created', videoIds: [] }],
        totalCount: 1,
      },
      success: true,
    });
    const { loader } = await importPlaylistsApiRoute();

    const response = await loader({
      request: new Request('http://localhost/api/playlists?q=vault'),
    } as never);

    expect(fakePlaylistServices.findPlaylists.execute).toHaveBeenCalledWith(expect.objectContaining({
      filters: expect.objectContaining({ searchQuery: 'vault' }),
      ownerId: 'owner-1',
    }));
    expect(response.status).toBe(200);
    await expect(response.json()).resolves.toEqual({
      filters: { genre: [], searchQuery: 'vault' },
      hasMore: false,
      pagination: { currentPage: 1, limit: 20, offset: 0, totalPages: 1 },
      playlists: [{ id: 'playlist-1', name: 'Vault', ownerId: 'owner-1', type: 'user_created', videoIds: [] }],
      success: true,
      totalCount: 1,
    });
  });

  test('create route preserves the current success payload shape', async () => {
    fakePlaylistServices.createPlaylist.execute.mockResolvedValue({
      data: {
        autoGeneratedThumbnail: false,
        message: 'Playlist "Vault" created successfully',
        playlistId: 'playlist-1',
      },
      success: true,
    });
    const { action } = await importPlaylistsApiRoute();

    const response = await action({
      request: new Request('http://localhost/api/playlists', {
        body: JSON.stringify({
          name: 'Vault',
          type: 'user_created',
        }),
        headers: { 'Content-Type': 'application/json' },
        method: 'POST',
      }),
    } as never);

    expect(fakePlaylistServices.createPlaylist.execute).toHaveBeenCalledWith(expect.objectContaining({
      name: 'Vault',
      ownerId: 'owner-1',
      type: 'user_created',
    }));
    expect(response.status).toBe(200);
    await expect(response.json()).resolves.toEqual({
      autoGeneratedThumbnail: false,
      message: 'Playlist "Vault" created successfully',
      playlistId: 'playlist-1',
      success: true,
    });
  });

  test('detail loader preserves the current success payload shape', async () => {
    fakePlaylistServices.getPlaylistDetails.execute.mockResolvedValue({
      data: {
        permissions: {
          canAddVideos: true,
          canDelete: true,
          canEdit: true,
          canShare: true,
        },
        playlist: {
          createdAt: new Date('2026-03-08T00:00:00.000Z'),
          id: 'playlist-1',
          isPublic: false,
          name: 'Vault',
          ownerId: 'owner-1',
          stats: {
            completionRate: 0,
            id: 'playlist-1',
            lastUpdated: new Date('2026-03-08T00:00:00.000Z'),
            popularityScore: 1,
            totalDuration: 0,
            totalVideos: 1,
            totalViews: 0,
          },
          type: 'user_created',
          updatedAt: new Date('2026-03-08T00:00:00.000Z'),
          videoIds: ['video-1'],
          videos: [{
            duration: 90,
            id: 'video-1',
            position: 1,
            title: 'playtime',
          }],
        },
        relatedPlaylists: [],
        stats: {
          completionRate: 0,
          id: 'playlist-1',
          lastUpdated: new Date('2026-03-08T00:00:00.000Z'),
          popularityScore: 1,
          totalDuration: 0,
          totalVideos: 1,
          totalViews: 0,
        },
        videoPagination: {
          hasMore: false,
          limit: 50,
          offset: 0,
          total: 1,
        },
      },
      success: true,
    });
    const { loader } = await importPlaylistDetailApiRoute();

    const response = await loader({
      params: { id: 'playlist-1' },
      request: new Request('http://localhost/api/playlists/playlist-1?includeVideos=true&includeStats=true'),
    } as never);

    expect(fakePlaylistServices.getPlaylistDetails.execute).toHaveBeenCalledWith(expect.objectContaining({
      ownerId: 'owner-1',
      playlistId: 'playlist-1',
    }));
    expect(response.status).toBe(200);
    await expect(response.json()).resolves.toEqual(expect.objectContaining({
      permissions: expect.objectContaining({ canEdit: true }),
      playlist: expect.objectContaining({
        id: 'playlist-1',
        name: 'Vault',
        videos: [expect.objectContaining({ id: 'video-1', title: 'playtime' })],
      }),
      success: true,
      videoPagination: expect.objectContaining({ total: 1 }),
    }));
  });

  test('route returns auth response without touching services when unauthorized', async () => {
    requireProtectedApiSessionMock.mockResolvedValue(new Response('unauthorized', { status: 401 }));
    const { loader } = await importPlaylistsApiRoute();

    const response = await loader({
      request: new Request('http://localhost/api/playlists'),
    } as never);

    expect(response.status).toBe(401);
    await expect(response.text()).resolves.toBe('unauthorized');
    expect(fakePlaylistServices.findPlaylists.execute).not.toHaveBeenCalled();
  });
});
